version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-svg
    versions:
    - 11.2.4
    - 11.2.5
    - 12.0.0
    - 13.0.0
    - 13.0.1
  - dependency-name: vercel
    versions:
    - 21.2.1
    - 21.2.2
    - 21.3.0
